# ============ language model configurations ============ 
# Set up OpenAI API key.
OPENAI_API_KEY="sk-G3PsDts9TMYJG3Qqz4AUdZ7ggde0hrWAeTbZUBMqcEH3vQIq"
OPENAI_API_KEY_3="sk-abD8p2hdW9cMs6PzwxVqmIm8BVDYedAtHPeGykejJCZ9gYMf"
OPENAI_APTI_KEY_1 = "sk-h5hgDnSlvQL2S0KpMmTpilSUjBj7gI2q7zLATnjUa8eN4b8u"
OPENAI_APTI_KEY_2 = "sk-p1gETIwEDqon4QKfUgJeiKAh3T8VgTJ1Nr9Y0R1nYjaXH71T"
OPENAI_APTI_KEY_3.5 = "sk-jHpJxWTEhpszNgWkP6y47ebIw1NKHjnZ4ABgoE6Z9z3XcPxh"





# If you are using the API service provided by OpenAI, include the following line:
OPENAI_API_TYPE="openai"

# Set up retieval key
YDC_API_KEY = "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"

API_BASE = "http://chatapi.littlewheat.com/v1/"
# API_BASE_2= "https://xiaoai.plus/v1/"
AZURE_API_VERSION = ""
TAVILY_API_KEY = "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"


OPENAI_API_TEMPERATURE = "1.0"
OPENAI_API_TOP_P = "0.9"






DEEPSEEK_API_KEY = "sk-fd6c7d7a75b349339b05f08029d21be2"
DEEPSEEK_API_BASE = "https://api.deepseek.com"

DEEPSEEK_API_KEY_SILI = "sk-azgbmhxhahrptafwxnkbfxbygvcronetbjeanargnvikzmbr"
DEEPSEEK_API_KEY_ONE = "sk-32ce77b8b9994fa3a18af04e99233d84"
DEEPSEEK_API_KEY_SILI_TWO = "sk-huhxoxbthdujjkohoeyxflvaihmfgijmldxcyzjnjrfpskmw"
DEEPSEEK_API_KEY_SILI_THREE = "sk-zddbbyamyqsgjqxojtufjimmldwpobitrxlikebefrtvmpow"
DEEPSEEK_API_KEY_SILI_FOUR = "sk-gvdqsxvjqzebtzcmycgorapgokrjfkyyevvdqygiophcazwg"